'use client';
import { useEffect,useRef,useState,type CSSProperties } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDownToLine, ArrowUpRight, Mail, MessageCircle, Phone, Users, Star } from 'lucide-react';
import { FaGlobe } from 'react-icons/fa';
import { cardTextColor,type CardContent } from '@/lib/cards/contracts';
import './cards.css';
const socialMarks={Instagram:'instagram',Facebook:'facebook',LinkedIn:'linkedin',TikTok:'tiktok',YouTube:'youtube',X:'x'};
export default function PublicCard({content:c,token,referral=false}:{content:CardContent;token?:string;referral?:boolean}) {
 const [failedLogo,setFailedLogo]=useState('');
 const visit=useRef('');const [form,setForm]=useState(false);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
 const [referralUrl,setReferralUrl]=useState('');const linkKey=useRef('');const submission=useRef('');
 async function request(action:string,body:unknown){const response=await fetch(`/api/cards/public/${token}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:true});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please retry');return data;}
 function track(type:string,detail?:string){if(!token)return;if(!visit.current)visit.current=crypto.randomUUID();void request('events',{visitId:visit.current,eventId:crypto.randomUUID(),type,detail}).catch(()=>{});}
 useEffect(()=>{
  if(!token)return;visit.current=crypto.randomUUID();let timer:ReturnType<typeof setTimeout>|undefined;let opened=false;
  const visible=()=>{clearTimeout(timer);if(!opened&&document.visibilityState==='visible')timer=setTimeout(()=>{opened=true;void request('events',{visitId:visit.current,eventId:crypto.randomUUID(),type:'qualified_open',visibleMs:2000}).catch(()=>{opened=false;});},2000);};
  visible();document.addEventListener('visibilitychange',visible);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',visible);};
  // The token defines a visit; rendering or form edits must not restart it.
  // eslint-disable-next-line react-hooks/exhaustive-deps
 },[token]);
 async function shareReferral(){if(!token)return;setBusy(true);try{linkKey.current||=crypto.randomUUID();const result=await request('referral-link',{idempotencyKey:linkKey.current});setReferralUrl(result.url);if(navigator.share)await navigator.share({title:`${c.name}'s business card`,url:result.url});else {await navigator.clipboard.writeText(result.url);setStatus('Referral link copied');}}catch(e){setStatus(e instanceof Error?e.message:'Please retry');}finally{setBusy(false);}}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setBusy(true);setStatus('');const values=new FormData(event.currentTarget);try{submission.current||=crypto.randomUUID();await request('referrals',{submissionId:submission.current,name:values.get('name'),phone:values.get('phone')||'',email:values.get('email')||'',note:values.get('note')||'',referrerName:values.get('referrerName')||'',permission:values.get('permission')==='on'});setForm(false);setStatus('Thank you! Your details have been sent.');}catch(e){setStatus(e instanceof Error?e.message:'Please retry');}finally{setBusy(false);}}
 const theme=c.theme;const text=theme?cardTextColor(theme.background):undefined;
 const style=theme?{'--card-bg':theme.background,'--card-text':text,'--card-muted':text==='#ffffff'?'#c4c6cd':'#555963','--card-line':text==='#ffffff'?'#ffffff30':'#00000020','--card-soft':text==='#ffffff'?'#ffffff0c':'#00000006','--card-accent':theme.accent,'--card-accent-text':cardTextColor(theme.accent),'--card-header':theme.header,'--card-header-text':cardTextColor(theme.header)} as CSSProperties:undefined;
 return <main className="wolfcard-shell" style={style}><article className="wolfcard">
 <header className="wolfcard-cover"><div className="wolfcard-company-brand">{c.companyLogo&&failedLogo!==c.companyLogo?<Image unoptimized src={c.companyLogo} width={180} height={64} alt={c.company?`${c.company} logo`:'Company logo'} className="wolfcard-company-logo" onError={()=>setFailedLogo(c.companyLogo??'')}/>:c.company?<span className="wolfcard-company-wordmark">{c.company}</span>:null}</div><div className="wolfcard-cover-lines" aria-hidden="true"/></header>
 <div className="wolfcard-profile">
 {c.photo?<Image unoptimized width={100} height={100} src={c.photo} alt={c.name} className="wolfcard-avatar"/>:<div className="wolfcard-avatar wolfcard-initials" aria-hidden="true">{c.name.split(/\s+/).map(s=>s[0]).slice(0,2).join('')}</div>}
 <h1>{c.name}</h1><p className="wolfcard-role">{c.title}</p>{c.company&&<p className="wolfcard-company">{c.company}</p>}
 {token?<a className="wolfcard-save" href={`/api/cards/public/${token}/contact`} onClick={()=>track('contact_downloaded')}><ArrowDownToLine size={20} aria-hidden="true"/>Save Contact<ArrowUpRight className="wolfcard-save-arrow" size={19} aria-hidden="true"/></a>:<button className="wolfcard-save" disabled><ArrowDownToLine size={20} aria-hidden="true"/>Save Contact</button>}
 {c.socials.length>0&&<nav className="wolfcard-socials" aria-label="Social media">{c.socials.map(s=>{return <a key={s.platform} href={s.url} target="_blank" rel="noopener noreferrer" className={`wolfcard-social wolfcard-social-${s.platform.toLowerCase()}`} onClick={()=>track(s.platform==='Website'?'website_clicked':'social_clicked',s.platform)}><span className="wolfcard-social-icon"><>{s.platform==='Website'?<FaGlobe aria-hidden="true"/>:<Image unoptimized src={`/brand/social/${socialMarks[s.platform]}.svg`} width={25} height={25} alt="" aria-hidden="true" className="wolfcard-brand-mark"/>}</></span><span>{s.platform}</span></a>;})}</nav>}
 </div>
 <nav aria-label="Contact" className="wolfcard-actions">{c.phone&&<><a href={`tel:${c.phone.replace(/[^+\d]/g,'')}`} onClick={()=>track('call_clicked')}><Phone size={18} aria-hidden="true"/>Call</a><a href={`sms:${c.phone.replace(/[^+\d]/g,'')}`} onClick={()=>track('text_clicked')}><MessageCircle size={18} aria-hidden="true"/>Text</a></>}{c.email&&<a href={`mailto:${c.email}`} onClick={()=>track('email_clicked')}><Mail size={18} aria-hidden="true"/>Email</a>}</nav>
 {c.bio&&<section><h2>About me</h2><p className="wolfcard-bio">{c.bio}</p></section>}
 {c.reviewUrl&&<section><a className="wolfcard-button" href={c.reviewUrl} target="_blank" rel="noopener noreferrer" onClick={()=>track('review_clicked')}><Star size={18} aria-hidden="true"/>Read or leave a review<ArrowUpRight size={17} aria-hidden="true"/></a></section>}
 <section className="wolfcard-referrals"><span className="wolfcard-referral-icon" aria-hidden="true"><Users size={22}/></span><h2>{referral?'Let’s connect':'Know someone I can help?'}</h2><p className="wolfcard-referral-copy">{referral?'Leave your details and I’ll be in touch.':'A simple introduction can make all the difference.'}</p><button disabled={!token} className="wolfcard-button wolfcard-primary" onClick={()=>{setForm(true);track('referral_started');}}>{referral?'Send my details':'Send a Referral'}</button><button className="wolfcard-button" disabled={!token||busy} onClick={shareReferral}>Share a referral link</button>{referralUrl&&<input aria-label="Your referral link" readOnly value={referralUrl}/>}
 {form&&<form onSubmit={submit}><label>{referral?'Your name':'Referral name'}<input name="name" required maxLength={100} autoComplete="name"/></label><label>Phone<input name="phone" type="tel" maxLength={40}/></label><label>Email<input name="email" type="email" maxLength={254}/></label><p>Enter a phone number or email address.</p>{!referral&&<label>Your name (optional)<input name="referrerName" maxLength={100}/></label>}<label>Note<textarea name="note" maxLength={2000}/></label><label className="wolfcard-check"><input type="checkbox" name="permission" required/>{referral?'I agree to be contacted about my request.':'I have permission to share these details so this representative can follow up.'}</label><button className="wolfcard-button wolfcard-primary" disabled={busy}>{busy?'Sending…':'Send details'}</button><button type="button" className="wolfcard-button" onClick={()=>setForm(false)}>Cancel</button></form>}
 <p role="status">{status}</p></section><footer>Link views and button interactions are recorded to help this representative follow up. Forwarded links remain associated with their original share. <Link href="/privacy">Privacy</Link><p>Made with WolfGrid</p></footer>
 </article></main>;
}
