/**
 * AI Flyer Generation Client
 * 
 * Uses Google Gemini API to generate flyer design concepts.
 * Note: Gemini generates text/descriptions. Image URLs are placeholders
 * that can be replaced with actual image generation API calls later.
 */

import { getGeminiModel } from "./googleGemini";

export type FlyerGenerationRequest = {
  orientation: 'horizontal' | 'vertical';
  size: string; // e.g. "8.5x5.5"
  finish: 'glossy' | 'matte';
  campaignType: 'just-listed' | 'just-sold' | 'open-house' | 'farming' | 'service-business';
  address?: string;
  price?: string;
  beds?: number | null;
  baths?: number | null;
  sqft?: number | null;
  cta: string;
  brandColor: string; // hex
  style: 'clean-minimal' | 'bold-color' | 'luxury' | 'modern-gradient';
  tone: 'professional' | 'friendly' | 'high-energy' | 'luxury';
  mediaUrls?: string[]; // optional image URLs
};

export type FlyerDesign = {
  id: string;
  imageUrl: string;
  description?: string;
};

export type FlyerGenerationResponse = {
  designs: FlyerDesign[];
};

/**
 * Build a prompt for Gemini based on flyer request
 * Exported for use in frontend to build prompts for image generation
 */
export function buildFlyerPrompt(payload: FlyerGenerationRequest): string {
  const {
    orientation,
    size,
    finish,
    campaignType,
    address,
    price,
    beds,
    baths,
    sqft,
    cta,
    brandColor,
    style,
    tone,
  } = payload;

  let prompt = `Generate 3 different flyer design concepts for a real estate marketing flyer.

Specifications:
- Orientation: ${orientation}
- Size: ${size} inches
- Finish: ${finish}
- Campaign Type: ${campaignType.replace(/-/g, ' ')}
- Style: ${style.replace(/-/g, ' ')}
- Tone: ${tone.replace(/-/g, ' ')}
- Brand Color: ${brandColor}
- Call to Action: ${cta}`;

  if (address) prompt += `\n- Property Address: ${address}`;
  if (price) prompt += `\n- Price: ${price}`;
  if (beds) prompt += `\n- Bedrooms: ${beds}`;
  if (baths) prompt += `\n- Bathrooms: ${baths}`;
  if (sqft) prompt += `\n- Square Feet: ${sqft}`;

  prompt += `\n\nFor each of the 3 designs, provide:
1. A brief description (2-3 sentences) of the design concept
2. Key visual elements and layout approach
3. How it incorporates the brand color and style

Format your response as a JSON array with objects containing "description" fields.`;

  return prompt;
}

/**
 * Generate flyer designs using Google Gemini API
 * 
 * @param payload - The flyer generation request payload
 * @returns Promise resolving to the API response with generated designs
 * @throws Error if API key is missing or API call fails
 */
export async function generateFlyerDesigns(
  payload: FlyerGenerationRequest
): Promise<FlyerGenerationResponse> {
  // 1. Build prompt
  const prompt = buildFlyerPrompt(payload);

  // 2. Get Gemini model using SDK
  const model = getGeminiModel("gemini-1.5-flash");

  try {
    // 3. Generate content using SDK
    const result = await model.generateContent([
      {
        role: "user",
        parts: [{ text: prompt }],
      },
    ]);

    // 4. Extract text from Gemini response
    const text = result.response.text();

    // 5. Parse response text
    let descriptions: string[] = [];
    try {
      // Try to parse JSON from response
      const jsonMatch = text.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        descriptions = parsed.map((item: any) => item.description || JSON.stringify(item));
      } else {
        // Fallback: split by common patterns
        const lines = text.split(/\n+/).filter((line: string) => line.trim().length > 20);
        descriptions = lines.slice(0, 3);
      }
    } catch (parseError) {
      console.warn('Failed to parse Gemini response, using fallback descriptions');
      descriptions = [
        'Modern design with clean typography and strategic use of brand colors',
        'Bold layout with vibrant imagery and compelling call-to-action placement',
        'Elegant composition balancing visual hierarchy and information density',
      ];
    }

    // 7. Generate design objects with placeholder images
    // In a real implementation, these would be generated by an image API
    const designs: FlyerDesign[] = descriptions.slice(0, 3).map((description, index) => ({
      id: `design-${Date.now()}-${index}`,
      imageUrl: `https://via.placeholder.com/600x800/${payload.brandColor.replace('#', '')}/FFFFFF?text=Design+${index + 1}`,
      description: description.substring(0, 200), // Limit description length
    }));

    return { designs };
  } catch (error) {
    // Enhanced error handling
    if (error instanceof Error) {
      console.error('AI flyer generation error:', {
        message: error.message,
        stack: error.stack,
        error,
      });
      throw error;
    }
    throw new Error(`Failed to call AI service: ${String(error)}`);
  }
}

// Export legacy names for backward compatibility
export type NanoBananaRequest = FlyerGenerationRequest;
export type NanoBananaDesign = FlyerDesign;
export type NanoBananaResponse = FlyerGenerationResponse;
export const generateNanoBananaFlyers = generateFlyerDesigns;
