import assert from 'node:assert/strict';
import { applicationStorageKey, persistApplication, restoreApplication, type ApplicationPayload } from '../application-request';
const ids = Array.from({ length: 7 }, () => crypto.randomUUID());
const rows = new Map<string, string>();
const store = { getItem: (key: string) => rows.get(key) ?? null, setItem: (key: string, value: string) => { rows.set(key, value); }, removeItem: (key: string) => { rows.delete(key); } };
const key = applicationStorageKey(...ids.slice(0, 4) as [string, string, string, string]);
const payload: ApplicationPayload = { requestId: ids[4], version: 3, contactId: ids[5], addressId: ids[6], saveNote: true, actions: [{ proposalIndex: 2, dueAt: '2026-10-07T12:30:00Z' }] };
assert.equal(restoreApplication(store, key), null);
persistApplication(store, key, payload);
assert.deepEqual(restoreApplication(store, key), payload);
persistApplication(store, key, JSON.parse(JSON.stringify(payload)));
assert.throws(() => persistApplication(store, key, { ...payload, requestId: crypto.randomUUID() }));
assert.deepEqual(restoreApplication(store, key), payload);
assert.equal(restoreApplication(store, applicationStorageKey(crypto.randomUUID(), ids[1], ids[2], ids[3])), null);
assert.throws(() => applicationStorageKey('invalid', ids[1], ids[2], ids[3]));
store.removeItem(key); assert.equal(restoreApplication(store, key), null);
store.setItem(key, '{"requestId":"corrupt"}'); assert.throws(() => restoreApplication(store, key));
assert.throws(() => persistApplication({ ...store, setItem: () => { throw new Error('Storage unavailable'); } }, applicationStorageKey(ids[1], ids[0], ids[2], ids[3]), payload));
console.log('Web exact application persistence, owner scope, replacement protection, invalid storage and clearing checks passed');
