import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import pg from 'pg';

async function main() {
const dir = mkdtempSync(join(tmpdir(), 'wolfgrid-field-pg-'));
const pgData = join(dir, 'data');
function command(name: string, args: string[]) {
  const result = spawnSync(name, args, { encoding: 'utf8' });
  if (result.status !== 0) throw new Error(`${name} failed: ${result.stderr}`);
}
let started = false;
const enginePath = process.env.WOLFGRID_PGLITE_MODULE;
const embedded = enginePath ? new (await import(enginePath)).PGlite() : null;
const client = embedded ? {
  connect: async () => undefined,
  query: async (sql: string, params?: unknown[]) => params ? embedded.query(sql, params) : (await embedded.exec(sql)).at(-1) || { rows: [] },
  end: async () => embedded.close(),
} : new pg.Client({ host: dir, port: 55439, database: 'postgres', user: process.env.USER });
try {
  if (!embedded) {
    command('initdb', ['-D', pgData, '-A', 'trust', '--no-locale']);
    command('pg_ctl', ['-D', pgData, '-l', join(dir, 'server.log'), '-o', `-k ${dir} -p 55439 -c listen_addresses=''`, '-w', 'start']);
    started = true;
  }
  await client.connect();
  await client.query(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
    CREATE SCHEMA auth; CREATE SCHEMA storage;
    CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE TABLE public.workspaces(id uuid PRIMARY KEY);
    CREATE TABLE public.workspace_members(workspace_id uuid,user_id uuid);
    CREATE TABLE public.sessions(id uuid PRIMARY KEY,workspace_id uuid,user_id uuid,target_building_ids text[],campaign_id uuid);
    CREATE TABLE public.campaigns(id uuid PRIMARY KEY,workspace_id uuid);
    CREATE TABLE public.campaign_addresses(id uuid PRIMARY KEY,campaign_id uuid,gers_id text,address text);
    CREATE TABLE public.contacts(id uuid PRIMARY KEY,user_id uuid,workspace_id uuid,address_id uuid,lead_kind text);
    CREATE TABLE public.contact_activities(id uuid PRIMARY KEY,contact_id uuid,type text CHECK(type IN ('knock','call','flyer','note','text','email','meeting')),note text,timestamp timestamptz);
    CREATE TABLE public.field_sales_settings(workspace_id uuid PRIMARY KEY,enabled boolean,currency text,timezone text);
    CREATE TABLE public.field_sales_tasks(id uuid PRIMARY KEY,workspace_id uuid,contact_id uuid,user_id uuid,title text CHECK(length(trim(title)) BETWEEN 1 AND 200),kind text CHECK(kind IN ('call','email','text','visit','task')),due_at timestamptz NOT NULL);
    CREATE TABLE public.field_sales_pipeline_events(id uuid DEFAULT gen_random_uuid(),workspace_id uuid,contact_id uuid,actor_id uuid,action text,detail jsonb);
    CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);`);
  for (const file of ['20261006130000_plaud_field_recordings.sql', '20261006140000_field_recording_worker.sql', '20261006141000_field_recording_finalize.sql', '20261006150000_field_conversation_draft_review.sql', '20261006160000_field_conversation_assignment.sql', '20261006170000_field_conversation_apply.sql', '20261006171000_field_conversation_application_options.sql', '20261006180000_field_conversation_split.sql', '20261006190000_field_conversation_merge.sql', '20261006200000_field_recording_deletion.sql']) {
    await client.query(readFileSync(join(process.cwd(), 'supabase/migrations', file), 'utf8'));
  }
  const user = '98b71ba8-cfec-4c79-b2be-1d99d8f9f438';
  const workspace = 'fdd5b548-2cfd-4b87-bfbb-9127e30bc895';
  const session = 'f940ed9e-caaa-4f0e-a4bb-55f99b9a8f9a';
  const recording = '48ea868b-f40c-4a75-aaca-88d63ed71741';
  const chunk = '9f95c163-efba-4406-bf62-eeb03c7b486c';
  await client.query('INSERT INTO auth.users VALUES($1);', [user]);
  await client.query('INSERT INTO workspaces VALUES($1);', [workspace]);
  await client.query('INSERT INTO workspace_members VALUES($1,$2);', [workspace, user]);
  await client.query('INSERT INTO sessions(id,workspace_id,user_id) VALUES($1,$2,$3);', [session, workspace, user]);
  await client.query("INSERT INTO field_recordings(id,workspace_id,user_id,session_id,device_serial,timezone,started_at) VALUES($1,$2,$3,$4,'pin','America/Toronto',now())", [recording, workspace, user, session]);
  const event = { id: '581516da-e5da-4e16-9f79-7638880c2d28', kind: 'start_requested', sequence: 0, occurredAt: '2026-10-06T14:00:00Z' };
  const append = () => client.query('SELECT append_field_recording_event($1,$2,$3) AS result', [recording, user, event]);
  assert.equal((await append()).rows[0].result.capture_state, 'start_requested');
  assert.equal((await append()).rows[0].result.last_event_sequence, 0);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_recording_events')).rows[0].n, 1);
  await assert.rejects(client.query('SELECT append_field_recording_event($1,$2,$3)', [recording, user, { ...event, kind: 'start_confirmed' }]));
  await assert.rejects(client.query('SELECT append_field_recording_event($1,$2,$3)', [recording, '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632', event]));
  const paused = (await client.query('SELECT append_field_recording_event($1,$2,$3) AS result', [recording, user, { id: 'fead51b9-2757-49c9-b27e-cc8f15d4d14b', kind: 'paused', sequence: 1, occurredAt: '2026-10-06T14:00:10Z', providerRecordingId: 'one' }])).rows[0].result;
  assert.equal(paused.capture_state, 'paused');
  const resumed = (await client.query('SELECT append_field_recording_event($1,$2,$3) AS result', [recording, user, { id: '16867c4c-afc8-4161-9a30-033d4d19b62f', kind: 'resumed', sequence: 2, occurredAt: '2026-10-06T14:00:20Z', providerRecordingId: 'one' }])).rows[0].result;
  assert.equal(resumed.capture_state, 'recording');
  await client.query("INSERT INTO field_recording_chunks(id,recording_id,provider_recording_id,storage_path) VALUES($1,$2,'one','private.mp3')", [chunk, recording]);
  const enqueue = () => client.query('SELECT enqueue_field_recording_chunk($1,$2,$3) AS result', [recording, user, chunk]);
  const job = (await enqueue()).rows[0].result;
  assert.equal((await enqueue()).rows[0].result.id, job.id);
  const claim = (await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result;
  assert.equal(claim.id, job.id);
  assert.equal((await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result, null);
  assert.equal((await client.query('SELECT commit_field_recording_job($1,$2,$3) AS result', [job.id, '118d72bb-b9aa-407f-adc1-2e3a9fcfa106', { status: 'done' }])).rows[0].result, false);
  assert.equal((await client.query('SELECT commit_field_recording_job($1,$2,$3) AS result', [job.id, claim.lease_token, { nextStage: 'transcribe' }])).rows[0].result, true);
  await client.query('SELECT claim_field_recording_job()');
  await client.query("UPDATE field_recording_jobs SET lease_until=now()-interval '1 minute'");
  assert.equal((await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result, null);
  assert.equal((await client.query('SELECT error_code FROM field_recording_jobs')).rows[0].error_code, 'submission_outcome_unknown');
  await client.query("UPDATE field_recording_jobs SET status='pending',stage='analyze'");
  let finalClaim = (await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result;
  const conversation = 'e44a5b04-d8e5-42cc-9dcd-c23886409310';
  await client.query('INSERT INTO field_conversations(id,recording_id,chunk_id) VALUES($1,$2,$3)', [conversation, recording, chunk]);
  await client.query("UPDATE field_conversations SET summary='Reviewed summary',note='Keep my note',action_proposals='[{\"kind\":\"task\"}]'::jsonb WHERE id=$1", [conversation]);
  await client.query('SELECT commit_field_recording_job($1,$2,$3)', [job.id, finalClaim.lease_token, { nextStage: 'write', conversation: { id: conversation, expectedVersion: 1, analysis: { outcome: 'follow_up' } } }]);
  let preserved = (await client.query('SELECT * FROM field_conversations WHERE id=$1', [conversation])).rows[0];
  assert.equal(preserved.note, 'Keep my note');
  assert.equal(preserved.summary, 'Reviewed summary');
  assert.equal(preserved.action_proposals.length, 1);
  assert.equal(preserved.version, 2);
  finalClaim = (await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result;
  const secondChunk = '15a062ac-f8aa-4b4b-b989-18a4f631b355';
  await client.query("INSERT INTO field_recording_chunks(id,recording_id,provider_recording_id,storage_path) VALUES($1,$2,'two','second.mp3')", [secondChunk, recording]);
  const secondJob = (await client.query('SELECT enqueue_field_recording_chunk($1,$2,$3) AS result', [recording, user, secondChunk])).rows[0].result;
  await client.query('SELECT commit_field_recording_job($1,$2,$3)', [job.id, finalClaim.lease_token, { status: 'done', processingState: 'needs_review', conversation: { id: conversation, expectedVersion: 1, note: 'Stale worker overwrite' } }]);
  preserved = (await client.query('SELECT * FROM field_conversations WHERE id=$1', [conversation])).rows[0];
  assert.equal(preserved.note, 'Keep my note');
  assert.equal(preserved.version, 2);
  assert.equal((await client.query('SELECT processing_state FROM field_recordings')).rows[0].processing_state, 'transferring');
  const secondClaim = (await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result;
  assert.equal(secondClaim.id, secondJob.id);
  await client.query('SELECT commit_field_recording_job($1,$2,$3)', [secondJob.id, secondClaim.lease_token, { nextStage: 'transcribe' }]);
  assert.equal((await client.query('SELECT processing_state FROM field_recordings')).rows[0].processing_state, 'transcription_pending');
  await client.query('SELECT claim_field_recording_job()');
  await client.query("UPDATE field_recording_jobs SET lease_until=now()-interval '1 minute' WHERE id=$1", [secondJob.id]);
  await client.query('SELECT claim_field_recording_job()');
  assert.equal((await client.query('SELECT processing_state FROM field_recordings')).rows[0].processing_state, 'error');
  await client.query('DELETE FROM field_recording_jobs WHERE id=$1', [secondJob.id]);
  await client.query('DELETE FROM field_recording_chunks WHERE id=$1', [secondChunk]);
  await client.query("UPDATE field_recording_jobs SET status='pending',stage='analyze' WHERE id=$1", [job.id]);
  finalClaim = (await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result;
  const assignmentConversation = 'a8d95c19-8a77-4b2d-81a7-1fc3f1e5a106';
  const target = '25313b68-2cfb-437b-b552-9b7fcdcb1b67';
  await client.query('UPDATE sessions SET target_building_ids=$1 WHERE id=$2', [[target], session]);
  await client.query("UPDATE field_recording_chunks SET transcription_state='SUCCESS' WHERE id=$1", [chunk]);
  await client.query("INSERT INTO field_conversations(id,recording_id,chunk_id,note,analysis) VALUES($1,$2,$3,'Old draft','{}')", [assignmentConversation, recording, chunk]);
  const assign = (version: number, targetId: string | null, consent: string, permission: boolean) => client.query('SELECT assign_field_conversation($1,$2,$3,$4,$5,$6,$7) AS result', [recording, assignmentConversation, user, version, targetId, consent, permission]);
  await assert.rejects(assign(1, target, 'granted', false));
  await assert.rejects(assign(1, 'b95df2ed-e38e-44f7-9f63-7d54a0a786c1', 'granted', true));
  const assigned = (await assign(1, target, 'granted', true)).rows[0].result;
  assert.equal(assigned.target_confirmed, true);
  assert.equal(assigned.target_id, target);
  assert.equal(assigned.consent, 'granted');
  assert.equal(assigned.note, null);
  assert.equal(assigned.analysis, null);
  assert.equal(assigned.assignment_history.length, 1);
  await assert.rejects(client.query('SELECT assign_field_conversation($1,$2,$3,$4,$5,$6,$7)', [recording, assignmentConversation, '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632', 2, target, 'granted', true]));
  const unassigned = (await assign(2, null, 'unknown', false)).rows[0].result;
  assert.equal(unassigned.target_confirmed, false);
  assert.equal(unassigned.target_id, null);
  assert.equal(unassigned.consent, 'unknown');
  assert.equal(unassigned.assignment_history.length, 2);
  assert.equal(unassigned.assignment_history[1].previousConsent, 'granted');
  const campaign = 'ed53332c-ac88-40c1-b9a2-d48c991b41d5';
  const manual = 'e502d163-f2a4-4e6e-a575-25252983a791';
  await client.query('INSERT INTO campaigns VALUES($1,$2)', [campaign, workspace]);
  await client.query('UPDATE sessions SET campaign_id=$1 WHERE id=$2', [campaign, session]);
  await client.query("INSERT INTO campaign_addresses VALUES($1,$2,NULL,'12 Main Street')", [manual, campaign]);
  await assert.rejects(assign(3, manual, 'granted', true));
  await client.query('SELECT append_field_recording_event($1,$2,$3)', [recording, user, { id: 'c1e65158-e6f0-4fcd-ad53-bf52f2a83548', sequence: 3, kind: 'door_started', targetId: manual, consent: 'granted', occurredAt: '2026-10-06T14:01:00Z' }]);
  const manualAssignment = (await assign(3, manual, 'granted', true)).rows[0].result;
  assert.equal(manualAssignment.target_id, manual);
  assert.equal(manualAssignment.assignment_history.length, 3);
  const foreignCampaign = 'cc65f326-9c9c-4973-a355-d3c0ac83300f';
  const foreignAddress = '6050bafb-26ac-4149-9875-11973d5739e8';
  await client.query('INSERT INTO campaigns VALUES($1,$2)', [foreignCampaign, workspace]);
  await client.query("INSERT INTO campaign_addresses VALUES($1,$2,NULL,'Other campaign door')", [foreignAddress, foreignCampaign]);
  await client.query('SELECT append_field_recording_event($1,$2,$3)', [recording, user, { id: 'dc2e467b-ef1b-4d55-81c1-0ce84f919cff', sequence: 4, kind: 'door_started', targetId: foreignAddress, consent: 'granted', occurredAt: '2026-10-06T14:02:00Z' }]);
  await assert.rejects(assign(4, foreignAddress, 'granted', true));
  await assert.rejects(assign(1, target, 'granted', true));
  assert.equal((await client.query('SELECT commit_field_recording_job($1,$2,$3) AS result', [job.id, finalClaim.lease_token, { status: 'done' }])).rows[0].result, false);
  assert.equal((await client.query('SELECT stage FROM field_recording_jobs WHERE id=$1', [job.id])).rows[0].stage, 'analyze');
  finalClaim = (await client.query('SELECT claim_field_recording_job() AS result')).rows[0].result;
  await client.query('DELETE FROM field_conversations WHERE id=$1', [assignmentConversation]);
  const draft = { summary: 'Requested call', note: 'Call next week', evidence: [], actions: [] };
  const review = (version: number, operation: string, owner = user) => client.query('SELECT review_field_conversation_draft($1,$2,$3,$4,$5,$6) AS result', [recording, conversation, owner, version, operation, operation === 'save_draft' ? draft : null]);
  await assert.rejects(review(2, 'save_draft', '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632'));
  assert.equal((await review(2, 'save_draft')).rows[0].result.version, 3);
  await assert.rejects(review(2, 'save_draft'));
  assert.equal((await review(3, 'reject')).rows[0].result.review_state, 'rejected');
  await assert.rejects(review(4, 'save_draft'));
  const applyConversation = '7f39eaec-101e-4f77-8894-d7da1c7a5a7b';
  const contactId = 'ae3f9c5f-9b7b-4b96-ac12-74098167127f';
  await client.query("INSERT INTO contacts VALUES($1,$2,$3,$4,'field')", [contactId, user, workspace, manual]);
  const quote = 'Call me tomorrow and book an appointment';
  const evidence = [{ segmentId: 'segment-one', quote }];
  const proposals = [{ kind: 'call', title: 'Call resident', dueAt: null, evidence }, { kind: 'appointment', title: 'Appointment with resident', dueAt: null, evidence }, { kind: 'do_not_contact', title: 'Do not contact', dueAt: null, evidence }];
  await client.query("INSERT INTO field_conversations(id,recording_id,chunk_id,target_id,target_confirmed,consent,note,segments,evidence,action_proposals) VALUES($1,$2,$3,$4,true,'granted','Requested callback',$5,$6,$7)", [applyConversation, recording, chunk, manual, [{ id: 'segment-one', text: quote }], evidence, proposals]);
  const approvalOptions = (await client.query('SELECT field_conversation_application_options($1,$2,$3) AS result', [recording, applyConversation, user])).rows[0].result;
  assert.equal(approvalOptions.households.length, 1);
  assert.equal(approvalOptions.households[0].addressId, manual);
  assert.equal(approvalOptions.households[0].label, '12 Main Street');
  assert.equal(approvalOptions.households[0].contacts[0].id, contactId);
  assert.equal(approvalOptions.taskCreationEnabled, false);
  await assert.rejects(client.query('SELECT field_conversation_application_options($1,$2,$3)', [recording, applyConversation, '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632']));
  const applicationPayload = { requestId: 'ab9a0b61-90f0-477c-911f-c00b082c33f2', version: 1, contactId, addressId: manual, saveNote: true, actions: [{ proposalIndex: 0, dueAt: '2026-10-07T14:00:00Z' }, { proposalIndex: 1, dueAt: '2026-10-08T14:00:00Z' }] };
  const apply = (payload = applicationPayload) => client.query('SELECT apply_field_conversation($1,$2,$3,$4) AS result', [recording, applyConversation, user, payload]);
  await assert.rejects(apply({ ...applicationPayload, addressId: foreignAddress }));
  const unlinkedContact = '3db2d8bc-7649-4b73-98ce-2b60923b37cf';
  const otherOwnerContact = '3626fb3e-a9ac-4d99-b746-db68a20a3319';
  await client.query("INSERT INTO contacts VALUES($1,$2,$3,$4,'field')", [unlinkedContact, user, workspace, foreignAddress]);
  await client.query("INSERT INTO contacts VALUES($1,$2,$3,$4,'field')", [otherOwnerContact, '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632', workspace, manual]);
  await assert.rejects(apply({ ...applicationPayload, contactId: unlinkedContact }));
  await assert.rejects(apply({ ...applicationPayload, contactId: otherOwnerContact }));
  await assert.rejects(apply({ ...applicationPayload, actions: [{ proposalIndex: 2, dueAt: '2026-10-07T14:00:00Z' }] }));
  await assert.rejects(apply({ ...applicationPayload, actions: [{ proposalIndex: 0, dueAt: '' }] }));
  assert.equal((await client.query('SELECT count(*)::int AS n FROM contact_activities')).rows[0].n, 0);
  await assert.rejects(apply()); // Sales is not configured: no partial note/appointment write.
  assert.equal((await client.query('SELECT count(*)::int AS n FROM contact_activities')).rows[0].n, 0);
  await client.query("INSERT INTO field_sales_settings VALUES($1,true,'CAD','America/Toronto')", [workspace]);
  await assert.rejects(apply({ ...applicationPayload, actions: [applicationPayload.actions[0], applicationPayload.actions[0]] }));
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_sales_tasks')).rows[0].n, 0);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM contact_activities')).rows[0].n, 0);
  await client.query('UPDATE field_conversations SET evidence=$1 WHERE id=$2', [[{ segmentId: 'segment-one', quote: 'Fabricated quote' }], applyConversation]);
  await assert.rejects(apply());
  await client.query('UPDATE field_conversations SET evidence=$1 WHERE id=$2', [evidence, applyConversation]);
  const filteredOptions = (await client.query('SELECT field_conversation_application_options($1,$2,$3) AS result', [recording, applyConversation, user])).rows[0].result;
  assert.equal(filteredOptions.households[0].contacts.length, 1);
  assert.equal(filteredOptions.taskCreationEnabled, true);
  const applied = (await apply()).rows[0].result;
  assert.equal(applied.conversation.review_state, 'approved');
  assert.equal(applied.taskIds.length, 1);
  assert.equal(applied.appointmentIds.length, 1);
  assert.ok(applied.noteActivityId);
  assert.deepEqual((await apply()).rows[0].result, applied);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM contact_activities')).rows[0].n, 2);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_sales_tasks')).rows[0].n, 1);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_conversation_applications')).rows[0].n, 1);
  await assert.rejects(apply({ ...applicationPayload, requestId: 'af9d567a-3838-4135-97f3-20b57cdd6bbd' }));
  await client.query('DELETE FROM field_conversation_applications WHERE conversation_id=$1', [applyConversation]);
  await client.query('DELETE FROM field_conversations WHERE id=$1', [applyConversation]);
  const splitSource = 'aabf1470-30c7-4baf-afce-320117e14955';
  const splitRequest = '97884016-46de-40ac-aef4-dd50456fe7cf';
  const splitSegments = [{ id: 'split-one', text: 'First door', startMs: 0, endMs: 2000, speaker: null }, { id: 'split-two', text: 'Second door', startMs: 3000, endMs: 5000, speaker: null }];
  await client.query("UPDATE field_recording_chunks SET transcription_state='SUCCESS' WHERE id=$1", [chunk]);
  await client.query("UPDATE field_recording_jobs SET stage='write',status='done' WHERE chunk_id=$1", [chunk]);
  await client.query("INSERT INTO field_conversations(id,recording_id,chunk_id,segments,consent,target_confirmed,note,timing) VALUES($1,$2,$3,$4,'granted',true,'Original draft',$5)", [splitSource, recording, chunk, JSON.stringify(splitSegments), { clock: 'campaign' }]);
  const split = (version = 1, boundary = 'split-two', request = splitRequest) => client.query('SELECT split_field_conversation($1,$2,$3,$4,$5,$6) AS result', [recording, user, request, splitSource, version, boundary]);
  await assert.rejects(split(2));
  await assert.rejects(split(1, 'split-one'));
  await assert.rejects(client.query('SELECT split_field_conversation($1,$2,$3,$4,$5,$6)', [recording, '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632', splitRequest, splitSource, 1, 'split-two']));
  await client.query("UPDATE field_conversations SET review_state='approved' WHERE id=$1", [splitSource]);
  await assert.rejects(split());
  await client.query("UPDATE field_conversations SET review_state='pending' WHERE id=$1", [splitSource]);
  const blocker = 'a531cdd7-5c76-4cb0-8c28-af8de357cdb2';
  await client.query('INSERT INTO field_conversations(id,recording_id,chunk_id,segments) VALUES($1,$2,$3,$4)', [blocker, recording, chunk, JSON.stringify([splitSegments[1]])]);
  await assert.rejects(split());
  assert.equal((await client.query('SELECT review_state,version FROM field_conversations WHERE id=$1', [splitSource])).rows[0].review_state, 'pending');
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_conversation_restructures')).rows[0].n, 0);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_conversations WHERE $1=ANY(parent_conversation_ids)', [splitSource])).rows[0].n, 0);
  await client.query('DELETE FROM field_conversations WHERE id=$1', [blocker]);
  const splitResult = (await split()).rows[0].result;
  assert.equal(splitResult.conversations.length, 2);
  assert.equal(splitResult.history.length, 1);
  assert.equal(splitResult.history[0].id, splitSource);
  assert.equal(splitResult.history[0].review_state, 'superseded');
  assert.deepEqual(splitResult.history[0].segments, splitSegments);
  assert.deepEqual(splitResult.conversations.flatMap((child: { segments: unknown[] }) => child.segments).sort((a: { id: string }, b: { id: string }) => a.id.localeCompare(b.id)), splitSegments);
  for (const child of splitResult.conversations) { assert.equal(child.consent, 'unknown'); assert.equal(child.target_confirmed, false); assert.equal(child.note, null); assert.deepEqual(child.parent_conversation_ids, [splitSource]); assert.equal(child.timing.speechMs, null); }
  assert.equal((await client.query('SELECT review_state FROM field_conversations WHERE id=$1', [splitSource])).rows[0].review_state, 'superseded');
  await client.query('UPDATE field_conversations SET note=$2,version=version+1 WHERE id=$1', [splitResult.conversations[0].id, 'Reviewed child']);
  const splitReplay = (await split()).rows[0].result;
  assert.equal(splitReplay.replayed, true); assert.equal(splitReplay.conversations[0].note, 'Reviewed child');
  await assert.rejects(split(1, 'split-one'));
  await assert.rejects(split(1, 'split-two', '431de74b-6fbd-4e27-b930-02e031e93d4e'));
  const mergeRequest = 'efa420f7-e724-4e21-99b0-9603302e004b';
  const mergeSources = splitReplay.conversations.map((child: { id: string; version: number }) => ({ id: child.id, version: child.version }));
  const merge = (sources = mergeSources) => client.query('SELECT merge_field_conversations($1,$2,$3,$4::jsonb) AS result', [recording, user, mergeRequest, JSON.stringify(sources)]);
  await assert.rejects(merge(mergeSources.map((child: { id: string; version: number }) => ({ ...child, version: 99 }))));
  await assert.rejects(merge([mergeSources[0], mergeSources[0]]));
  await assert.rejects(client.query('SELECT merge_field_conversations($1,$2,$3,$4::jsonb)', [recording, '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632', mergeRequest, JSON.stringify(mergeSources)]));
  await client.query('UPDATE field_conversations SET review_state=$2 WHERE id=$1', [mergeSources[0].id, 'approved']);
  await assert.rejects(merge());
  await client.query('UPDATE field_conversations SET review_state=$2 WHERE id=$1', [mergeSources[0].id, 'pending']);
  const originalMergeSegments = (await client.query('SELECT segments FROM field_conversations WHERE id=$1', [mergeSources[0].id])).rows[0].segments;
  await client.query("UPDATE field_conversations SET segments='[]'::jsonb WHERE id=$1", [mergeSources[0].id]);
  await assert.rejects(merge());
  await client.query('UPDATE field_conversations SET segments=$2::jsonb WHERE id=$1', [mergeSources[0].id, JSON.stringify(originalMergeSegments)]);
  await client.query(`CREATE FUNCTION reject_test_merge_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
    IF cardinality(NEW.parent_conversation_ids)=2 THEN RAISE EXCEPTION 'Test merge insert failure'; END IF;
    RETURN NEW; END $$;
    CREATE TRIGGER reject_test_merge_insert BEFORE INSERT ON field_conversations FOR EACH ROW EXECUTE FUNCTION reject_test_merge_insert();`);
  await assert.rejects(merge());
  const retainedSources = (await client.query('SELECT id,version,review_state FROM field_conversations WHERE id=ANY($1::uuid[])', [mergeSources.map((child: { id: string }) => child.id)])).rows;
  assert.equal(retainedSources.length, 2);
  for (const retained of retainedSources) {
    assert.equal(retained.review_state, 'pending');
    assert.equal(retained.version, mergeSources.find((child: { id: string }) => child.id === retained.id).version);
  }
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_conversation_restructures WHERE request_id=$1', [mergeRequest])).rows[0].n, 0);
  await client.query('DROP TRIGGER reject_test_merge_insert ON field_conversations; DROP FUNCTION reject_test_merge_insert();');
  const merged = (await merge()).rows[0].result;
  assert.equal(merged.conversations.length, 1);
  assert.equal(merged.history.length, 2);
  assert.equal(merged.history.find((original: { id: string }) => original.id === mergeSources[0].id).note, 'Reviewed child');
  assert.ok(merged.history.every((original: { review_state: string }) => original.review_state === 'superseded'));
  assert.deepEqual(merged.conversations[0].segments, splitSegments);
  assert.deepEqual(merged.conversations[0].parent_conversation_ids, mergeSources.map((child: { id: string }) => child.id));
  assert.equal(merged.conversations[0].consent, 'unknown');
  assert.equal(merged.conversations[0].note, null);
  assert.equal(merged.conversations[0].timing.speechMs, null);
  assert.equal((await merge()).rows[0].result.replayed, true);
  await client.query('UPDATE field_conversations SET note=$2,version=version+1 WHERE id=$1', [merged.conversations[0].id, 'Reviewed merged note']);
  assert.equal((await merge()).rows[0].result.conversations[0].note, 'Reviewed merged note');
  await assert.rejects(merge([...mergeSources].reverse()));
  await client.query('DELETE FROM field_conversation_restructures WHERE request_id=$1', [mergeRequest]);
  await client.query('DELETE FROM field_conversations WHERE id=$1', [merged.conversations[0].id]);
  await client.query('DELETE FROM field_conversation_restructures WHERE request_id=$1', [splitRequest]);
  await client.query('DELETE FROM field_conversations WHERE id=$1 OR $1=ANY(parent_conversation_ids)', [splitSource]);
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006201000_field_recording_chunk_guard.sql'), 'utf8'));
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006202000_field_recording_upload_expiry.sql'), 'utf8'));
  assert.equal((await client.query('SELECT reserve_field_recording_upload($1,$2,$3) AS result', [recording, user, chunk])).rows[0].result, true);
  const deletionRequest = '70b53c1d-a1df-463d-82a9-e83dff807976';
  const deletion = (request = deletionRequest, owner = user) => client.query('SELECT request_field_recording_deletion($1,$2,$3) AS result', [recording, owner, request]);
  await assert.rejects(deletion(deletionRequest, '4fd7d0d9-a737-4ffb-84f9-d18d1ec17632'));
  await client.query("UPDATE field_recordings SET capture_state='recording' WHERE id=$1", [recording]);
  await assert.rejects(deletion());
  await client.query("UPDATE field_recordings SET capture_state='stopped' WHERE id=$1", [recording]);
  await client.query(`CREATE FUNCTION reject_test_deletion() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
    IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN RAISE EXCEPTION 'Test deletion failure'; END IF;
    RETURN NEW; END $$;
    CREATE TRIGGER reject_test_deletion BEFORE UPDATE ON field_recordings FOR EACH ROW EXECUTE FUNCTION reject_test_deletion();`);
  await assert.rejects(deletion());
  assert.equal((await client.query('SELECT deleted_at FROM field_recordings WHERE id=$1', [recording])).rows[0].deleted_at, null);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].n, 0);
  await client.query('DROP TRIGGER reject_test_deletion ON field_recordings; DROP FUNCTION reject_test_deletion();');
  const deleted = (await deletion()).rows[0].result;
  const lateChunk = 'e5bdaab0-8692-4e6d-9558-bb17036ac5e8';
  await assert.rejects(client.query("INSERT INTO field_recording_chunks(id,recording_id,provider_recording_id,storage_path) SELECT $1,id,$2,workspace_id::text||'/'||user_id::text||'/'||id::text||'/'||$1::text||'.mp3' FROM field_recordings WHERE id=$3", [lateChunk, 'late-file', recording]));
  await assert.rejects(client.query('UPDATE field_recording_chunks SET storage_path=$2 WHERE recording_id=$1', [recording, 'foreign/path.mp3']));
  await assert.rejects(client.query('SELECT reserve_field_recording_upload($1,$2,$3)', [recording, user, chunk]));
  assert.equal((await client.query("SELECT storage_not_before > now()+interval '124 minutes' AS deferred FROM field_recording_deletions WHERE recording_id=$1", [recording])).rows[0].deferred, true);
  assert.equal(deleted.storageState, 'pending');
  assert.equal(deleted.providerState, 'pending');
  assert.equal((await deletion()).rows[0].result.replayed, true);
  await assert.rejects(deletion('095031dc-a074-4f76-b6db-d9fbeb653432'));
  assert.equal((await client.query('SELECT processing_state FROM field_recordings WHERE id=$1', [recording])).rows[0].processing_state, 'deleted');
  assert.equal((await client.query("SELECT count(*)::int AS n FROM field_recording_jobs WHERE recording_id=$1 AND status IN ('pending','running')", [recording])).rows[0].n, 0);
  const deletionManifest = (await client.query('SELECT manifest FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].manifest;
  assert.ok(deletionManifest.length > 0);
  assert.ok(deletionManifest.every((file: { storagePath: string }) => typeof file.storagePath === 'string'));
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006203000_field_recording_cleanup_retry.sql'), 'utf8'));
  await client.query('SELECT defer_field_recording_storage_cleanup($1)', [recording]);
  assert.equal((await client.query("SELECT storage_attempts=1 AND storage_retry_after BETWEEN now()+interval '59 seconds' AND now()+interval '61 seconds' AS deferred FROM field_recording_deletions WHERE recording_id=$1", [recording])).rows[0].deferred, true);
  assert.equal((await client.query("SELECT count(*)::int AS n FROM field_recording_deletions WHERE storage_state='pending' AND storage_retry_after<=now()", [])).rows[0].n, 0);
  await client.query('UPDATE field_recording_deletions SET storage_attempts=30 WHERE recording_id=$1', [recording]);
  await client.query('SELECT defer_field_recording_storage_cleanup($1)', [recording]);
  assert.equal((await client.query("SELECT storage_attempts=30 AND storage_retry_after BETWEEN now()+interval '3599 seconds' AND now()+interval '3601 seconds' AS capped FROM field_recording_deletions WHERE recording_id=$1", [recording])).rows[0].capped, true);
  await client.query("UPDATE field_recording_deletions SET storage_state='done' WHERE recording_id=$1", [recording]);
  const retryDeadline = (await client.query('SELECT storage_retry_after FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].storage_retry_after;
  await client.query('SELECT defer_field_recording_storage_cleanup($1)', [recording]);
  assert.deepEqual((await client.query('SELECT storage_retry_after FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].storage_retry_after, retryDeadline);
  await client.query('UPDATE field_recordings SET deleted_at=now()');
  await assert.rejects(review(4, 'reject'));
  assert.equal((await client.query('SELECT commit_field_recording_job($1,$2,$3) AS result', [job.id, finalClaim.lease_token, { conversations: [{ targetId: null, consent: 'unknown', segments: [], timing: {} }] }])).rows[0].result, false);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_conversations')).rows[0].n, 1);
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006204000_field_recording_content_purge.sql'), 'utf8'));
  const crmBefore = await client.query('SELECT to_jsonb(a) AS row FROM contact_activities a ORDER BY id');
  const tasksBefore = await client.query('SELECT to_jsonb(t) AS row FROM field_sales_tasks t ORDER BY id');
  await assert.rejects(client.query('SELECT complete_field_recording_storage_cleanup($1)', [lateChunk]));
  await assert.rejects(client.query('SELECT complete_field_recording_storage_cleanup($1)', [recording]));
  await client.query("UPDATE field_recording_deletions SET storage_not_before=now()-interval '1 second' WHERE recording_id=$1", [recording]);
  await client.query(`UPDATE field_recording_chunks SET transcript='{"text":"private transcript"}' WHERE recording_id=$1`, [recording]);
  await client.query(`CREATE FUNCTION reject_test_content_purge() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
    IF NEW.segments='[]'::jsonb THEN RAISE EXCEPTION 'Test purge failure'; END IF; RETURN NEW; END $$;
    CREATE TRIGGER reject_test_content_purge BEFORE UPDATE ON field_conversations FOR EACH ROW EXECUTE FUNCTION reject_test_content_purge();`);
  await assert.rejects(client.query('SELECT complete_field_recording_storage_cleanup($1)', [recording]));
  assert.equal((await client.query('SELECT transcript->>\'text\' AS text FROM field_recording_chunks WHERE id=$1', [chunk])).rows[0].text, 'private transcript');
  assert.equal((await client.query('SELECT content_purged_at FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].content_purged_at, null);
  await client.query('DROP TRIGGER reject_test_content_purge ON field_conversations; DROP FUNCTION reject_test_content_purge();');
  await client.query('SELECT complete_field_recording_storage_cleanup($1)', [recording]);
  assert.equal((await client.query("SELECT count(*)::int AS n FROM field_conversations WHERE recording_id=$1 AND (segments<>'[]' OR analysis IS NOT NULL OR summary IS NOT NULL OR note IS NOT NULL OR evidence IS NOT NULL OR action_proposals<>'[]')", [recording])).rows[0].n, 0);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_recording_chunks WHERE recording_id=$1 AND (transcript IS NOT NULL OR provider_upload IS NOT NULL OR provider_download_url IS NOT NULL)', [recording])).rows[0].n, 0);
  assert.equal((await client.query("SELECT count(*)::int AS n FROM field_conversation_applications a JOIN field_conversations c ON c.id=a.conversation_id WHERE c.recording_id=$1 AND a.result ? 'conversation'", [recording])).rows[0].n, 0);
  assert.deepEqual((await client.query('SELECT to_jsonb(a) AS row FROM contact_activities a ORDER BY id')).rows, crmBefore.rows);
  assert.deepEqual((await client.query('SELECT to_jsonb(t) AS row FROM field_sales_tasks t ORDER BY id')).rows, tasksBefore.rows);
  assert.deepEqual((await client.query('SELECT manifest FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].manifest, deletionManifest);
  const purgedAt = (await client.query('SELECT content_purged_at FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].content_purged_at;
  assert.ok(purgedAt);
  await client.query('SELECT complete_field_recording_storage_cleanup($1)', [recording]);
  assert.deepEqual((await client.query('SELECT content_purged_at FROM field_recording_deletions WHERE recording_id=$1', [recording])).rows[0].content_purged_at, purgedAt);
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006205000_field_recording_provider_limits.sql'), 'utf8'));
  const limitRecording = lateChunk;
  await client.query("INSERT INTO field_recordings(id,workspace_id,user_id,session_id,device_serial,timezone,started_at) VALUES($1,$2,$3,$4,'limit-pin','UTC',now())", [limitRecording, workspace, user, session]);
  const limitJob = async (stage: string) => (await client.query("INSERT INTO field_recording_jobs(recording_id,stage,deduplication_key,status,lease_token,lease_until) VALUES($1,$2,gen_random_uuid()::text,'running',gen_random_uuid(),now()+interval '5 minutes') RETURNING id,lease_token", [limitRecording, stage])).rows[0];
  const firstLimitJob = await limitJob('transcribe');
  const reserveLimit = async (job: { id: string; lease_token: string }, limit: number | null) => (await client.query('SELECT reserve_field_recording_provider_request($1,$2,$3) AS allowed', [job.id, job.lease_token, limit])).rows[0].allowed;
  assert.equal(await reserveLimit(firstLimitJob, 1), true);
  assert.equal(await reserveLimit(firstLimitJob, 1), true);
  const secondLimitJob = await limitJob('transcribe');
  assert.equal(await reserveLimit(secondLimitJob, 1), false);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_recording_provider_reservations')).rows[0].n, 1);
  assert.equal(await reserveLimit(await limitJob('analyze'), 1), true);
  assert.equal(await reserveLimit(await limitJob('write'), 0), false);
  await assert.rejects(reserveLimit({ ...secondLimitJob, lease_token: deletionRequest }, 10));
  await assert.rejects(reserveLimit(secondLimitJob, -1));
  await client.query("UPDATE field_recording_provider_reservations SET reserved_day=reserved_day-1 WHERE stage='transcribe'");
  assert.equal(await reserveLimit(secondLimitJob, 1), true);
  assert.equal((await client.query("SELECT has_function_privilege('authenticated','reserve_field_recording_provider_request(uuid,uuid,integer)','EXECUTE') AS allowed")).rows[0].allowed, false);
  const blockedLimitJob = await limitJob('write');
  await client.query('DELETE FROM workspace_members WHERE workspace_id=$1 AND user_id=$2', [workspace, user]);
  await assert.rejects(reserveLimit(blockedLimitJob, null));
  await client.query('INSERT INTO workspace_members VALUES($1,$2)', [workspace, user]);
  await client.query('UPDATE field_recordings SET deleted_at=now() WHERE id=$1', [limitRecording]);
  await assert.rejects(reserveLimit(blockedLimitJob, null));
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006206000_field_recording_provider_usage.sql'), 'utf8'));
  const usage = (await client.query('SELECT field_recording_provider_usage($1,$2) AS usage', [workspace, user])).rows[0].usage;
  assert.equal(usage.transcribe, 1); assert.equal(usage.analyze, 1); assert.equal(usage.write, 0);
  assert.equal(Date.parse(usage.resetAt) - Date.parse(`${usage.day}T00:00:00Z`), 86400000);
  await assert.rejects(client.query('SELECT field_recording_provider_usage($1,$2)', [workspace, deletionRequest]));
  assert.equal((await client.query("SELECT has_function_privilege('authenticated','field_recording_provider_usage(uuid,uuid)','EXECUTE') AS allowed")).rows[0].allowed, false);
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006207000_field_recording_retention.sql'), 'utf8'));
  const retentionRecording = 'c084ec69-39d6-465a-a7d8-46ae03f40c68';
  await client.query("INSERT INTO field_recordings(id,workspace_id,user_id,session_id,device_serial,timezone,started_at,ended_at,capture_state) VALUES($1,$2,$3,$4,'retention-pin','UTC',now()-interval '4 days',now()-interval '3 days','stopped')", [retentionRecording, workspace, user, session]);
  const expire = async (version: number) => (await client.query('SELECT expire_field_recording($1,$2) AS result', [retentionRecording, version])).rows[0].result;
  const policy = async (days: number | null, version: number) => (await client.query('SELECT set_field_recording_retention($1,$2,$3,$4) AS result', [workspace,user,days,version])).rows[0].result;
  assert.equal(await expire(0), null);
  assert.equal((await policy(null,0)).version,1);
  assert.equal(await expire(1), null);
  await assert.rejects(policy(0,1));
  await assert.rejects(policy(2,0));
  await assert.rejects(client.query('SELECT set_field_recording_retention($1,$2,2,0)', [workspace,deletionRequest]));
  await policy(4,1); assert.equal(await expire(2),null);
  await policy(2,2); assert.equal(await expire(2),null);
  await client.query("UPDATE field_recordings SET capture_state='paused' WHERE id=$1",[retentionRecording]);
  assert.equal(await expire(3),null);
  await client.query("UPDATE field_recordings SET capture_state='stopped' WHERE id=$1",[retentionRecording]);
  await client.query('DELETE FROM workspace_members WHERE workspace_id=$1 AND user_id=$2',[workspace,user]);
  assert.equal(await expire(3),null);
  await client.query('INSERT INTO workspace_members VALUES($1,$2)',[workspace,user]);
  await client.query('UPDATE field_recordings SET ended_at=NULL WHERE id=$1',[retentionRecording]);
  assert.equal(await expire(3),null);
  await client.query("UPDATE field_recordings SET ended_at=now()-interval '3 days' WHERE id=$1",[retentionRecording]);
  await client.query("CREATE FUNCTION reject_retention_deletion() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced retention failure'; END $$; CREATE TRIGGER reject_retention_deletion BEFORE INSERT ON field_recording_deletions FOR EACH ROW EXECUTE FUNCTION reject_retention_deletion();");
  await assert.rejects(expire(3));
  assert.equal((await client.query('SELECT deleted_at FROM field_recordings WHERE id=$1',[retentionRecording])).rows[0].deleted_at,null);
  await client.query('DROP TRIGGER reject_retention_deletion ON field_recording_deletions; DROP FUNCTION reject_retention_deletion();');
  const expired = await expire(3); assert.equal(expired.recordingId,retentionRecording);
  assert.equal(await expire(3),null);
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_recording_deletions WHERE recording_id=$1',[retentionRecording])).rows[0].n,1);
  assert.deepEqual((await client.query('SELECT to_jsonb(a) AS row FROM contact_activities a ORDER BY id')).rows,crmBefore.rows);
  assert.equal((await client.query("SELECT has_function_privilege('authenticated','expire_field_recording(uuid,bigint)','EXECUTE') AS allowed")).rows[0].allowed,false);
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006208000_field_recording_retention_dispatch.sql'), 'utf8'));
  const scheduledIds = ['a084ec69-39d6-465a-a7d8-46ae03f40001','a084ec69-39d6-465a-a7d8-46ae03f40002','a084ec69-39d6-465a-a7d8-46ae03f40003','a084ec69-39d6-465a-a7d8-46ae03f40004'];
  for (const id of scheduledIds) await client.query("INSERT INTO field_recordings(id,workspace_id,user_id,session_id,device_serial,timezone,started_at,ended_at,capture_state) VALUES($1,$2,$3,$4,'scheduled-pin','UTC',now()-interval '4 days',now()-interval '3 days','stopped')",[id,workspace,user,session]);
  const candidates = async (): Promise<Array<{ recording_id: string; policy_version: number }>> => (await client.query('SELECT * FROM field_recording_retention_candidates()')).rows;
  assert.equal((await candidates()).length,3);
  await client.query("UPDATE field_recordings SET capture_state='paused' WHERE id=$1",[scheduledIds[0]]);
  assert.deepEqual((await candidates()).map(row => row.recording_id),scheduledIds.slice(1));
  await client.query('SELECT defer_field_recording_retention($1,$2)',[scheduledIds[1],3]);
  assert.deepEqual((await candidates()).map(row => row.recording_id),scheduledIds.slice(2));
  const retryAt=(await client.query('SELECT retention_retry_after>now() AS future FROM field_recordings WHERE id=$1',[scheduledIds[1]])).rows[0]; assert.equal(retryAt.future,true);
  await policy(null,3); assert.equal((await candidates()).length,0);
  assert.equal((await client.query('SELECT expire_field_recording($1,3) AS result',[scheduledIds[2]])).rows[0].result,null);
  await policy(2,4);
  await client.query('DELETE FROM workspace_members WHERE workspace_id=$1 AND user_id=$2',[workspace,user]); assert.equal((await candidates()).length,0);
  await client.query('INSERT INTO workspace_members VALUES($1,$2)',[workspace,user]);
  assert.deepEqual((await candidates()).map(row => row.policy_version),[5,5]);
  await client.query('SELECT expire_field_recording($1,5)',[scheduledIds[2]]);
  assert.deepEqual((await candidates()).map(row => row.recording_id),[scheduledIds[3]]);
  for (const signature of ['field_recording_retention_candidates()','defer_field_recording_retention(uuid,bigint)']) assert.equal((await client.query("SELECT has_function_privilege('authenticated',$1,'EXECUTE') AS allowed",[signature])).rows[0].allowed,false);
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006209000_field_contact_preference_review.sql'), 'utf8'));
  const preferenceConversation='fa84ec69-39d6-465a-a7d8-46ae03f40001', preferenceChunk='fa84ec69-39d6-465a-a7d8-46ae03f40002';
  await client.query("INSERT INTO field_recording_chunks(id,recording_id,provider_recording_id,storage_path) VALUES($1,$2,'preference-file',$3)",[preferenceChunk,scheduledIds[3],`${workspace}/${user}/${scheduledIds[3]}/${preferenceChunk}.mp3`]);
  const preferenceEvidence=[{segmentId:'request',quote:'Please do not contact me again'}];
  await client.query("INSERT INTO field_conversations(id,recording_id,chunk_id,target_id,target_confirmed,consent,segments,action_proposals) VALUES($1,$2,$3,$4,true,'granted',$5,$6)",[preferenceConversation,scheduledIds[3],preferenceChunk,manual,[{id:'request',text:'Please do not contact me again'}],[{kind:'do_not_contact',title:'No further contact',dueAt:null,evidence:preferenceEvidence}]]);
  const preferencePayload={requestId:'fa84ec69-39d6-465a-a7d8-46ae03f40003',version:1,contactId,addressId:manual,proposalIndex:0,confirmed:true};
  const preference = async (payload: unknown = preferencePayload, owner=user) => (await client.query('SELECT review_field_contact_preference($1,$2,$3,$4) AS result',[scheduledIds[3],preferenceConversation,owner,payload])).rows[0].result;
  await assert.rejects(preference({...preferencePayload,confirmed:false}));
  await assert.rejects(preference({...preferencePayload,contactId:otherOwnerContact}));
  await assert.rejects(preference({...preferencePayload,contactId:unlinkedContact}));
  await assert.rejects(preference({...preferencePayload,addressId:foreignAddress}));
  await assert.rejects(preference({...preferencePayload,version:2}));
  await assert.rejects(preference({...preferencePayload,proposalIndex:1}));
  await assert.rejects(preference(preferencePayload,deletionRequest));
  await client.query("UPDATE field_conversations SET action_proposals=jsonb_set(action_proposals,'{0,evidence,0,quote}','\"invented\"') WHERE id=$1",[preferenceConversation]);
  await assert.rejects(preference());
  await client.query("UPDATE field_conversations SET action_proposals=jsonb_set(action_proposals,'{0,evidence}',$2) WHERE id=$1",[preferenceConversation,preferenceEvidence]);
  await client.query("CREATE FUNCTION reject_preference_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced audit failure'; END $$; CREATE TRIGGER reject_preference_audit BEFORE INSERT ON field_conversation_contact_preferences FOR EACH ROW EXECUTE FUNCTION reject_preference_audit();");
  await assert.rejects(preference());
  assert.equal((await client.query('SELECT do_not_contact FROM contacts WHERE id=$1',[contactId])).rows[0].do_not_contact,false);
  assert.equal((await client.query('SELECT version FROM field_conversations WHERE id=$1',[preferenceConversation])).rows[0].version,1);
  await client.query('DROP TRIGGER reject_preference_audit ON field_conversation_contact_preferences; DROP FUNCTION reject_preference_audit();');
  const preferenceResult=await preference(); assert.equal(preferenceResult.doNotContact,true); assert.equal(preferenceResult.version,2);
  assert.deepEqual(await preference(),preferenceResult);
  await assert.rejects(preference({...preferencePayload,requestId:deletionRequest}));
  assert.equal((await client.query('SELECT count(*)::int AS n FROM field_conversation_contact_preferences')).rows[0].n,1);
  assert.equal((await client.query('SELECT review_state FROM field_conversations WHERE id=$1',[preferenceConversation])).rows[0].review_state,'pending');
  assert.equal((await client.query("SELECT has_function_privilege('authenticated','review_field_contact_preference(uuid,uuid,uuid,jsonb)','EXECUTE') AS allowed")).rows[0].allowed,false);
  await assert.rejects(client.query("INSERT INTO field_sales_tasks(id,workspace_id,contact_id,user_id,title,kind,due_at) VALUES(gen_random_uuid(),$1,$2,$3,'Contact again','call',now()+interval '1 day')",[workspace,contactId,user]));
  await client.query("UPDATE field_conversations SET action_proposals=action_proposals||$2::jsonb,note='No further contact requested',evidence=$3 WHERE id=$1",[preferenceConversation,[{kind:'call',title:'Call again',dueAt:null,evidence:preferenceEvidence}],preferenceEvidence]);
  await assert.rejects(client.query('SELECT apply_field_conversation($1,$2,$3,$4)',[scheduledIds[3],preferenceConversation,user,{requestId:'fa84ec69-39d6-465a-a7d8-46ae03f40004',version:2,contactId,addressId:manual,saveNote:false,actions:[{proposalIndex:1,dueAt:'2026-10-07T14:00:00Z'}]}]));
  const preferenceNote=(await client.query('SELECT apply_field_conversation($1,$2,$3,$4) AS result',[scheduledIds[3],preferenceConversation,user,{requestId:'fa84ec69-39d6-465a-a7d8-46ae03f40004',version:2,contactId,addressId:manual,saveNote:true,actions:[]}])).rows[0].result;
  assert.ok(preferenceNote.noteActivityId);
  assert.equal((await client.query('SELECT do_not_contact FROM contacts WHERE id=$1',[contactId])).rows[0].do_not_contact,true);
  const approvedPreferenceConversation='fa84ec69-39d6-465a-a7d8-46ae03f40005';
  await client.query("INSERT INTO field_conversations(id,recording_id,chunk_id,target_id,target_confirmed,consent,review_state,segments,action_proposals) VALUES($1,$2,$3,$4,true,'granted','approved',$5,$6)",[approvedPreferenceConversation,scheduledIds[3],preferenceChunk,manual,[{id:'approved-request',text:'Please do not contact me again'}],[{kind:'do_not_contact',title:'No further contact',dueAt:null,evidence:[{segmentId:'approved-request',quote:'Please do not contact me again'}]}]]);
  const approvedOptions=(await client.query('SELECT field_conversation_application_options($1,$2,$3) AS result',[scheduledIds[3],approvedPreferenceConversation,user])).rows[0].result;
  assert.equal(approvedOptions.households[0].contacts[0].id,contactId);
  const approvedPreference=(await client.query('SELECT review_field_contact_preference($1,$2,$3,$4) AS result',[scheduledIds[3],approvedPreferenceConversation,user,{...preferencePayload,requestId:'fa84ec69-39d6-465a-a7d8-46ae03f40006'}])).rows[0].result;
  assert.equal(approvedPreference.doNotContact,true);
  assert.equal((await client.query('SELECT review_state FROM field_conversations WHERE id=$1',[approvedPreferenceConversation])).rows[0].review_state,'approved');
  await client.query(readFileSync(join(process.cwd(), 'supabase/migrations/20261006210000_field_recording_audio_budget.sql'), 'utf8'));
  const audioUsage = async (scope=workspace, owner=user) => (await client.query('SELECT field_recording_audio_usage($1,$2) AS usage',[scope,owner])).rows[0].usage;
  assert.equal((await audioUsage()).reservedMinutes,300); // The current-day legacy submission is conservatively charged five hours.
  assert.equal((await client.query("SELECT count(*)::int AS n FROM field_recording_provider_reservations WHERE stage='transcribe' AND reserved_audio_ms<>18000000")).rows[0].n,0);
  await client.query('UPDATE field_recording_provider_reservations SET reserved_day=(now() AT TIME ZONE \'UTC\')::date-1');
  const audioRecording=(await client.query("INSERT INTO field_recordings(id,workspace_id,user_id,session_id,device_serial,timezone,started_at) VALUES(gen_random_uuid(),$1,$2,$3,'audio-budget-pin','UTC',now()) RETURNING id",[workspace,user,session])).rows[0].id;
  const audioChunk=(await client.query("SELECT gen_random_uuid() AS id")).rows[0].id;
  await client.query("INSERT INTO field_recording_chunks(id,recording_id,provider_recording_id,storage_path) VALUES($1,$2,'audio-budget-file',$3)",[audioChunk,audioRecording,`${workspace}/${user}/${audioRecording}/${audioChunk}.mp3`]);
  const audioJob = async (stage='transcribe') => (await client.query("INSERT INTO field_recording_jobs(recording_id,chunk_id,stage,deduplication_key,status,lease_token,lease_until) VALUES($1,$2,$3,gen_random_uuid()::text,'running',gen_random_uuid(),now()+interval '5 minutes') RETURNING id,lease_token",[audioRecording,audioChunk,stage])).rows[0];
  const reserveAudio = async (job: {id:string;lease_token:string}, minutes: number|null, requests: number|null=null) => (await client.query('SELECT reserve_field_recording_provider_request($1,$2,$3,$4) AS allowed',[job.id,job.lease_token,requests,minutes])).rows[0].allowed;
  const measureAudio = (job: {id:string;lease_token:string}, duration:number|null) => client.query('SELECT checkpoint_field_recording_audio_duration($1,$2,$3)',[job.id,job.lease_token,duration]);
  const measuredJob=await audioJob('verify');
  await assert.rejects(reserveAudio(measuredJob,10));
  for (const duration of [null,0,18000001]) await assert.rejects(measureAudio(measuredJob,duration));
  await assert.rejects(measureAudio({...measuredJob,lease_token:deletionRequest},60001));
  await measureAudio(measuredJob,60001); await measureAudio(measuredJob,60001);
  await assert.rejects(measureAudio(measuredJob,1));
  await client.query("UPDATE field_recording_jobs SET stage='transcribe' WHERE id=$1",[measuredJob.id]);
  await assert.rejects(reserveAudio(measuredJob,10)); // A duration alone does not establish verified bytes.
  await client.query('UPDATE field_recording_chunks SET verified_at=now() WHERE id=$1',[audioChunk]);
  assert.equal(await reserveAudio(measuredJob,0),false);
  assert.equal(await reserveAudio(measuredJob,1),false);
  assert.equal(await reserveAudio(measuredJob,2,0),false);
  assert.equal((await audioUsage()).reservedMinutes,0);
  assert.equal(await reserveAudio(measuredJob,2,1),true); // 60.001 seconds rounds up to two minutes.
  assert.equal(await reserveAudio(measuredJob,0,0),true); // Exact reserved lease replay never creates another request.
  const nextAudioJob=await audioJob();
  assert.equal(await reserveAudio(nextAudioJob,3),false);
  assert.equal(await reserveAudio(nextAudioJob,4,1),false);
  assert.equal(await reserveAudio(nextAudioJob,4,2),true);
  assert.equal((await audioUsage()).reservedMinutes,4);
  await client.query("UPDATE field_recording_jobs SET status='error' WHERE id=$1",[measuredJob.id]);
  assert.equal((await audioUsage()).reservedMinutes,4); // Failures do not release reservations.
  const analyzingJob=await audioJob('analyze'); assert.equal(await reserveAudio(analyzingJob,0,10),true);
  await assert.rejects(measureAudio(analyzingJob,60001));
  assert.equal((await audioUsage()).reservedMinutes,4);
  const waitingJob=await audioJob();
  await assert.rejects(reserveAudio(waitingJob,-1)); await assert.rejects(reserveAudio(waitingJob,1000001));
  await assert.rejects(reserveAudio({...waitingJob,lease_token:deletionRequest},10));
  await client.query('UPDATE field_recording_jobs SET lease_until=NULL WHERE id=$1',[waitingJob.id]);
  await assert.rejects(reserveAudio(waitingJob,10)); await assert.rejects(measureAudio(waitingJob,60001));
  await client.query("UPDATE field_recording_jobs SET lease_until=now()-interval '1 minute' WHERE id=$1",[waitingJob.id]);
  await assert.rejects(reserveAudio(waitingJob,10));
  await client.query("UPDATE field_recording_jobs SET lease_until=now()+interval '5 minutes' WHERE id=$1",[waitingJob.id]);
  await client.query('DELETE FROM workspace_members WHERE workspace_id=$1 AND user_id=$2',[workspace,user]);
  await assert.rejects(reserveAudio(waitingJob,10)); await assert.rejects(measureAudio(waitingJob,60001)); await assert.rejects(audioUsage());
  await client.query('INSERT INTO workspace_members VALUES($1,$2)',[workspace,user]);
  await client.query("CREATE FUNCTION reject_audio_reservation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced audio audit failure'; END $$; CREATE TRIGGER reject_audio_reservation BEFORE INSERT ON field_recording_provider_reservations FOR EACH ROW EXECUTE FUNCTION reject_audio_reservation();");
  await assert.rejects(reserveAudio(waitingJob,10)); assert.equal((await audioUsage()).reservedMinutes,4);
  await client.query('DROP TRIGGER reject_audio_reservation ON field_recording_provider_reservations; DROP FUNCTION reject_audio_reservation();');
  const isolatedWorkspace=(await client.query('INSERT INTO workspaces VALUES(gen_random_uuid()) RETURNING id')).rows[0].id;
  await client.query('INSERT INTO workspace_members VALUES($1,$2)',[isolatedWorkspace,user]);
  assert.equal((await audioUsage(isolatedWorkspace)).reservedMinutes,0);
  await assert.rejects(audioUsage(isolatedWorkspace,deletionRequest));
  await client.query('UPDATE field_recordings SET deleted_at=now() WHERE id=$1',[audioRecording]);
  await assert.rejects(reserveAudio(waitingJob,10)); await assert.rejects(measureAudio(waitingJob,60001));
  assert.equal((await audioUsage()).reservedMinutes,4);
  assert.equal((await client.query("SELECT to_regprocedure('reserve_field_recording_provider_request(uuid,uuid,integer)') AS signature")).rows[0].signature,null);
  for (const signature of ['checkpoint_field_recording_audio_duration(uuid,uuid,bigint)','reserve_field_recording_provider_request(uuid,uuid,integer,integer)','field_recording_audio_usage(uuid,uuid)']) {
    assert.equal((await client.query("SELECT has_function_privilege('authenticated',$1,'EXECUTE') AS allowed",[signature])).rows[0].allowed,false);
    assert.equal((await client.query("SELECT has_function_privilege('service_role',$1,'EXECUTE') AS allowed",[signature])).rows[0].allowed,true);
  }
  console.log('PostgreSQL ownership, worker leases, CRM/restructure replay, deletion/content purge, request/audio-minute budgets and opt-in retention passed');
} finally {
  await client.end().catch(() => undefined);
  if (started) command('pg_ctl', ['-D', pgData, '-m', 'immediate', '-w', 'stop']);
  rmSync(dir, { recursive: true, force: true });
}
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
