import assert from 'node:assert/strict';
import { audioBudgetSummary, audioLimitStatus, checkedAudioBudget, checkedAudioUsage, transcriptionMinuteLimit, checkedProviderUsage, providerUsageSummary, nextProviderLimitDelay, providerRequestLimit, providerLimitStatus } from '../provider-limits';
assert.equal(providerRequestLimit('transcribe', {}), null);
assert.equal(providerRequestLimit('transcribe', { FIELD_RECORDING_DAILY_TRANSCRIPTION_REQUESTS: '0' }), 0);
assert.equal(providerRequestLimit('analyze', { FIELD_RECORDING_DAILY_JEV_REQUESTS: '20' }), 20);
assert.equal(providerRequestLimit('write', { FIELD_RECORDING_DAILY_WRITING_REQUESTS: '1000000' }), 1000000);
for (const value of ['', '-1', '1.5', ' 20', '01', 'NaN', '1000001']) assert.throws(() => providerRequestLimit('write', { FIELD_RECORDING_DAILY_WRITING_REQUESTS: value }));
assert.equal(nextProviderLimitDelay(new Date('2026-10-06T00:00:00Z')), 86400);
assert.equal(nextProviderLimitDelay(new Date('2026-10-06T23:59:59.900Z')), 1);
assert.equal(nextProviderLimitDelay(new Date('2026-12-31T23:59:00Z')), 60);
assert.deepEqual(providerLimitStatus({}), { configured: false, valid: true, transcribe: null, analyze: null, write: null });
assert.deepEqual(providerLimitStatus({ FIELD_RECORDING_DAILY_JEV_REQUESTS: '0' }), { configured: true, valid: true, transcribe: null, analyze: 0, write: null });
assert.equal(providerLimitStatus({ FIELD_RECORDING_DAILY_JEV_REQUESTS: 'invalid' }).valid, false);
const usage = { day: '2026-10-06', resetAt: '2026-10-07T00:00:00+00:00', transcribe: 1, analyze: 2, write: 0 };
assert.deepEqual(checkedProviderUsage(usage), usage);
assert.match(providerUsageSummary(usage, providerLimitStatus({ FIELD_RECORDING_DAILY_JEV_REQUESTS: '1' })), /Jev 2 \(0 remaining\)/);
assert.match(providerUsageSummary(usage, providerLimitStatus({ FIELD_RECORDING_DAILY_WRITING_REQUESTS: '0' })), /limit reached for writing/);
for (const invalid of [{ ...usage, day: '2026-02-30' }, { ...usage, resetAt: '2026-10-07T01:00:00Z' }, { ...usage, transcribe: -1 }, { ...usage, analyze: '1' }, { ...usage, write: Number.MAX_SAFE_INTEGER + 1 }, { ...usage, userId: 'private' }]) assert.throws(() => checkedProviderUsage(invalid));
console.log('Provider cap configuration and UTC reset boundaries passed');
assert.equal(transcriptionMinuteLimit({}), null);
assert.equal(transcriptionMinuteLimit({ FIELD_RECORDING_DAILY_TRANSCRIPTION_MINUTES: '0' }), 0);
assert.equal(transcriptionMinuteLimit({ FIELD_RECORDING_DAILY_TRANSCRIPTION_MINUTES: '1000000' }), 1000000);
for (const value of ['', '-1', '1.5', ' 20', '01', 'NaN', '1000001']) assert.throws(() => transcriptionMinuteLimit({ FIELD_RECORDING_DAILY_TRANSCRIPTION_MINUTES: value }));
assert.deepEqual(audioLimitStatus({}), { configured: false, valid: true, minutesPerDay: null });
assert.deepEqual(audioLimitStatus({ FIELD_RECORDING_DAILY_TRANSCRIPTION_MINUTES: 'bad' }), { configured: true, valid: false, minutesPerDay: null });
const audioUsage = { day: usage.day, resetAt: usage.resetAt, reservedMinutes: 12 };
const audioBudget = { configured: true, valid: true, minutesPerDay: 10, usage: audioUsage };
assert.deepEqual(checkedAudioBudget(audioBudget), audioBudget);
assert.match(audioBudgetSummary(audioBudget), /0 remaining/);
assert.match(audioBudgetSummary(audioBudget), /older unmeasured submissions reserve 300 minutes each/);
assert.match(audioBudgetSummary({ configured: false, valid: true, minutesPerDay: null, usage: null }), /usage is unavailable/);
for (const invalid of [{ ...audioUsage, day: '2026-02-30' }, { ...audioUsage, resetAt: '2026-10-07T01:00:00Z' }, { ...audioUsage, reservedMinutes: -1 }, { ...audioUsage, reservedMinutes: 0.5 }, { ...audioUsage, reservedMinutes: '1' }, { ...audioUsage, reservedMinutes: Number.MAX_SAFE_INTEGER + 1 }]) assert.throws(() => checkedAudioUsage(invalid));
for (const invalid of [{ ...audioBudget, configured: false }, { ...audioBudget, valid: false }, { ...audioBudget, minutesPerDay: null }, { ...audioBudget, minutesPerDay: 1000001 }, { ...audioBudget, extra: true }]) assert.throws(() => checkedAudioBudget(invalid));
console.log('Audio-minute caps, unavailable usage, strict status and conservative disclosure passed');
