import assert from 'node:assert/strict';
import { labelConversationTargets } from '../targets';
const building = '4f8ee83a-9ad2-4fb6-bcd5-409fe8aa1bb6';
const first = '4d4d5f9a-9a5b-4824-87ef-b3ac2b5a46b5';
const second = 'f2573919-05ee-4429-859d-7a3a5cf4f4dd';
const rows = [{ id: first, gers_id: building, address: ' 12 Main Street ' }, { id: second, gers_id: building, address: '14 Main Street' }];
const labels = labelConversationTargets([building.toUpperCase(), building, first, 'unknown'], rows);
assert.equal(labels.length, 3);
assert.equal(labels[0].ambiguous, true);
assert.equal(labels[0].label, '12 Main Street / 14 Main Street (multiple addresses)');
assert.deepEqual(labels[0].addressIds, [first, second]);
assert.equal(labels[1].label, '12 Main Street');
assert.equal(labels[1].ambiguous, false);
assert.deepEqual(labels[2].addressIds, []);
assert.equal(labels[2].label, 'Unresolved target unknown');
const unlabeled = labelConversationTargets([building], [{ id: first, gers_id: building, address: ' ' }]);
assert.equal(unlabeled[0].label, `Unresolved target ${building}`);
assert.deepEqual(unlabeled[0].addressIds, [first]);
console.log('Campaign target labels, identifier normalization, grouped household ambiguity and unresolved address handling passed');
