import assert from 'node:assert/strict';
import { alignAudioTimeline } from '../timeline';
import type { CaptureEvent, TranscriptSegment } from '../contracts';
const origin = '2026-10-06T12:00:00Z';
const event = (sequence: number, seconds: number, kind: CaptureEvent['kind'], providerRecordingId = 'one'): CaptureEvent => ({ id: String(sequence), sequence, occurredAt: new Date(Date.parse(origin) + seconds * 1000).toISOString(), kind, providerRecordingId });
const events = [event(0, 30, 'paused'), event(1, 90, 'resumed'), event(2, 120, 'paused'), event(3, 150, 'resumed')];
const segment = (id: string, startMs: number, endMs: number): TranscriptSegment => ({ id, startMs, endMs, text: 'Evidence', speaker: null });
const segments = [segment('before', 20000, 30000), segment('after', 30000, 40000), segment('later', 65000, 70000)];
const compacted = alignAudioTimeline(segments, events, origin, 0, 'one', 'pause_compacted');
assert.equal(compacted.aligned, true);
assert.deepEqual(compacted.segments.map(s => [s.startMs, s.endMs]), [[20000,30000],[90000,100000],[155000,160000]]);
assert.equal(compacted.pausedMs, 90000);
const crossing = alignAudioTimeline([segment('cross', 25000, 35000)], events.slice(0,2), origin, 0, 'one', 'pause_compacted');
assert.equal(crossing.timing(crossing.segments).spanMs, 70000);
assert.equal(crossing.timing(crossing.segments).speechMs, 10000);
const unknown = alignAudioTimeline(segments, events, origin, 0, 'one', 'unknown');
assert.equal(unknown.aligned, false);
assert.equal(unknown.timing(segments).clock, 'audio_unaligned');
assert.equal(unknown.conservativeEndMs(180000), 90000);
assert.deepEqual(alignAudioTimeline(segments, events, origin, 0, 'one', 'continuous').segments, segments);
assert.equal(alignAudioTimeline(segments, events, origin, 0, 'different-file', 'unknown').aligned, true);
assert.equal(alignAudioTimeline(segments, [event(0,30,'paused')], origin, 0, 'one', 'pause_compacted').aligned, false);
assert.equal(alignAudioTimeline(segments, [event(0,30,'paused'),event(1,20,'resumed')], origin, 0, 'one', 'pause_compacted').aligned, false);
const instant = alignAudioTimeline([segment('instant',30000,30000)],events.slice(0,2),origin,0,'one','pause_compacted');
assert.equal(instant.segments[0].startMs, 90000);
assert.equal(instant.segments[0].endMs, 90000);
const disconnected = alignAudioTimeline(segments,[...events,event(4,160,'disconnected')],origin,0,'one','pause_compacted');
assert.equal(disconnected.aligned, false);
const pending = alignAudioTimeline(segments,[event(0,30,'paused')],origin,0,'one','unknown');
assert.equal(pending.conservativeEndMs(100000),30000);
assert.equal(pending.conservativeEndMs(Infinity),Infinity);
assert.equal(alignAudioTimeline(segments,[event(0,30,'resumed')],origin,0,'one','continuous').aligned,false);
assert.throws(() => alignAudioTimeline(segments,events,'invalid',0,'one','unknown'));
console.log('Configured compacted/continuous mapping, pause boundaries, speech-time preservation, file identity and unknown timing safeguards passed');
