'use client';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { STORM_LAYER_GROUPS, WEATHER_SHADES, STRONGEST_STORM_SETTINGS, type StormGLSettings } from '@/lib/storm-maps/gl-settings';
type Props = { settings: StormGLSettings; onChange: (settings: StormGLSettings) => void; compact?: boolean };
export function StormGLSettingsPanel({ settings, onChange, compact = false }: Props) {
  const update = <K extends keyof StormGLSettings>(key: K, value: StormGLSettings[K]) => onChange({ ...settings, [key]: value });
  const row = (key: keyof StormGLSettings, title: string, detail?: string) => <div key={key} className="flex items-center justify-between gap-3 py-2"><div><p className="text-xs font-medium">{title}</p>{detail && <p className="mt-0.5 text-[10px] text-muted-foreground">{detail}</p>}</div><Switch checked={settings[key] === true} onCheckedChange={(value) => update(key, value)} aria-label={title} /></div>;
  return <div className="space-y-4">
    <div className="grid grid-cols-3 gap-1 rounded-xl bg-muted/30 p-1">{(['live', 'history', 'forecast'] as const).map((mode) => <button key={mode} type="button" onClick={() => update('mode', mode)} aria-pressed={settings.mode === mode} className={`rounded-lg px-1 py-2 text-xs font-semibold capitalize ${settings.mode === mode ? 'bg-cyan-300 text-slate-950' : 'hover:bg-muted/40'}`}>{mode}</button>)}</div>
    <label className="block text-xs font-medium">Color layer<select aria-label="Weather color layer" value={settings.shade} onChange={(e) => update('shade', e.target.value as StormGLSettings['shade'])} className="mt-2 h-10 w-full rounded-xl border border-current/15 bg-background px-3 text-xs">{WEATHER_SHADES.map((shade) => <option key={shade.id} value={shade.id}>{shade.label}</option>)}</select></label>
    <details open className="group"><summary className="cursor-pointer text-[10px] font-semibold uppercase tracking-widest text-cyan-600 dark:text-cyan-300">Storm intelligence</summary><div className="mt-1 divide-y divide-current/10">{STORM_LAYER_GROUPS.map((group) => row(group.key, group.title, group.detail))}</div></details>
    <details open={!compact}><summary className="cursor-pointer text-[10px] font-semibold uppercase tracking-widest text-cyan-600 dark:text-cyan-300">Official risk & campaign impact</summary><div className="mt-1 divide-y divide-current/10">{row('alerts', 'Official warnings & watches', 'NOAA/NWS & ECCC')}{row('outlook', 'Canadian severe storm outlook', 'ECCC experimental · hail, gusts & risk')}{row('reports', 'Recent storm reports', 'U.S. observed reports')}{row('impact', 'Campaign risk summary', 'Territories overlapping official risk areas')}{row('inspector', 'Click to inspect weather', 'Values, lightning, hail & storm-cell details')}</div></details>
    <details open={!compact}><summary className="cursor-pointer text-[10px] font-semibold uppercase tracking-widest text-cyan-600 dark:text-cyan-300">Display & playback</summary><div className="mt-3 space-y-4">
      {(['opacity', 'radarOpacity'] as const).map((key) => <div key={key}><div className="mb-2 flex justify-between text-[11px]"><span>{key === 'opacity' ? 'Background intensity' : 'Radar intensity'}</span><span>{settings[key]}%</span></div><Slider value={[settings[key]]} min={0} max={100} step={5} aria-label={key === 'opacity' ? 'Background intensity' : 'Radar intensity'} onValueChange={(value) => update(key, value[0])} /></div>)}
      <div className="grid grid-cols-2 gap-3"><label className="text-[11px]">Units<select aria-label="Weather units" value={settings.units} onChange={(e) => update('units', e.target.value as StormGLSettings['units'])} className="mt-1 h-9 w-full rounded-lg border border-current/15 bg-background px-2"><option value="metric">Metric</option><option value="imperial">Imperial</option></select></label><label className="text-[11px]">Playback<select aria-label="Weather playback speed" value={settings.speed} onChange={(e) => update('speed', Number(e.target.value))} className="mt-1 h-9 w-full rounded-lg border border-current/15 bg-background px-2"><option value={24}>Slow</option><option value={12}>Normal</option><option value={6}>Fast</option></select></label></div>
      <label className="block text-[11px]">History range<select aria-label="Weather history range" value={settings.historyHours} onChange={(e) => update('historyHours', Number(e.target.value))} className="mt-1 h-9 w-full rounded-lg border border-current/15 bg-background px-2"><option value={6}>Past 6 hours</option><option value={24}>Past 24 hours</option><option value={72}>Past 3 days</option></select></label>
    </div></details>
    <button type="button" onClick={() => onChange({ ...STRONGEST_STORM_SETTINGS })} className="w-full rounded-xl border border-cyan-400/40 bg-cyan-400/10 py-2.5 text-xs font-semibold text-cyan-700 dark:text-cyan-200">Restore strongest preset</button>
    <p className="text-[10px] text-muted-foreground">Saved for this workspace on this browser. Forecast mode shows model predictions; warnings, outlooks and reports retain their published valid times.</p>
  </div>;
}
